# Generated by Django 2.2.17 on 2020-11-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitle')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('job', models.TextField(verbose_name='Work')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('github', models.CharField(blank=True, max_length=100, null=True, verbose_name='Github')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('topimage', models.ImageField(upload_to='images', verbose_name='TopFigure')),
                ('subimage', models.ImageField(upload_to='images', verbose_name='SubFigure')),
            ],
        ),
    ]
